import Foundation

enum Curriculum {
    static let allDays: [CourseDay] = [
        makeDay(1, "Meet, move, and notice", "சந்திப்பு, நகர்வு", "main / tum / woh + go and come", "Catch who is moving and where the sentence is heading.", [
            prompt("office-jaana", "kal office jaana hai", "நாளை அலுவலகம் செல்ல வேண்டும்", "I have to go to the office tomorrow.", "jaana", "kal + place + jaana hai", "The ending hai often carries a need or plan.", "What is the speaker's plan?", ["Go to the office tomorrow", "Come home now", "Eat at the office", "Call a friend"], "Go to the office tomorrow", .meaning, .gist),
            prompt("ghar-aa-rahi", "main ghar aa rahi hoon", "நான் வீட்டிற்கு வந்து கொண்டிருக்கிறேன்", "I am coming home.", "aana", "main + aa rahi hoon", "The sound aa- points to aana, to come.", "Which action is happening now?", ["Coming home", "Going to work", "Drinking water", "Waiting outside"], "Coming home", .meaning, .verbFamilies),
            prompt("kya-hua", "kya hua?", "என்ன நடந்தது?", "What happened?", "hona", "kya + hua", "hua is a past form of hona, to happen / be.", "What does the question ask?", ["What happened?", "Where are you going?", "What do you want?", "Who came?"], "What happened?", .meaning, .anchors),
            prompt("paani-chahiye", "mujhe paani chahiye", "எனக்கு தண்ணீர் வேண்டும்", "I need water.", "chahiye", "mujhe + thing + chahiye", "chahiye is a useful need/request anchor.", "What does the speaker need?", ["Water", "A ticket", "A phone", "Food"], "Water", .anchor, .anchors)
        ], roleplay("day1-home", "At home", "Your friend is checking if you are on your way home.", "ghar aa rahi ho?", "நீ வீட்டிற்கு வருகிறாயா?", "Are you coming home?", ["Haan, bas aa rahi hoon.", "Nahi, paani chahiye.", "Kal office gaya.", "Kya hua?"], "Haan, bas aa rahi hoon.", "ஆம், வந்து கொண்டிருக்கிறேன்.", "Yes, I am on my way.", "Listen for aa- in aana and rahi hoon for an action happening now.") ),
        makeDay(2, "Home anchors", "வீட்டு முக்கிய சொற்கள்", "ghar, room, darwaaza, andar, baahar", "Recognize the place and direction before translating the rest.", [
            prompt("d2-1", "woh ghar ke andar hai", "அவர் வீட்டிற்குள் இருக்கிறார்", "They are inside the house.", "ghar", "ghar + ke andar", "andar means inside; it often follows a place.", "Where is the person?", ["Inside the house", "Outside the office", "At the station", "In the market"], "Inside the house", .meaning, .anchors),
            prompt("d2-2", "darwaaza band kar do", "கதவை மூடி விடுங்கள்", "Please close the door.", "karna", "thing + action + kar do", "kar do is a friendly spoken request to do something.", "What should happen to the door?", ["Close it", "Open it", "Paint it", "Move it"], "Close it", .reply, .response),
            prompt("d2-3", "main baahar jaa rahi hoon", "நான் வெளியே செல்கிறேன்", "I am going outside.", "jaana", "main + baahar + jaa rahi hoon", "baahar means outside; jaa- is the go family.", "Which place clue did you hear?", ["baahar", "andar", "ghar", "room"], "baahar", .anchor, .anchors),
            prompt("d2-4", "room mein koi hai", "அறையில் யாரோ இருக்கிறார்", "Someone is in the room.", "hona", "place + mein + hai", "hai marks a present state or location.", "What is the time clue?", ["Present / now", "Past", "Future", "A request"], "Present / now", .timeClue, .gist)
        ], roleplay("day2-door", "At the door", "Your housemate asks why the door is still open.", "darwaaza khula hai?", "கதவு திறந்திருக்கிறதா?", "Is the door open?", ["Haan, abhi band kar deti hoon.", "Kal office jaana hai.", "Mujhe chai chahiye.", "Woh ghar gaya."], "Haan, abhi band kar deti hoon.", "ஆம், இப்போது மூடுகிறேன்.", "Yes, I will close it now.", "A short reply can carry the whole context; listen for abhi (now) and band (closed).")),
        makeDay(3, "Eat, drink, and ask", "சாப்பாடு, குடிப்பு, கேட்பது", "khaana, peena, chahiye, thoda", "Ask for food or drink and catch whether someone already ate.", [
            prompt("khana-khaaya", "maine khaana khaaya", "நான் சாப்பாடு சாப்பிட்டேன்", "I ate food.", "khaana", "maine + thing + khaaya", "khaaya is a common past form in the khaana family.", "Has the speaker eaten?", ["Yes, already", "No, tomorrow", "They are asking for water", "They are leaving"], "Yes, already", .timeClue, .gist),
            prompt("chai-peena", "chai peena hai", "தேநீர் குடிக்க வேண்டும்", "I have to drink tea / need to have tea.", "peena", "thing + peena hai", "peena is to drink; hai makes the need/plan frame.", "What is the intent?", ["Drink tea", "Cook rice", "Buy a ticket", "Go outside"], "Drink tea", .meaning, .verbFamilies),
            prompt("d3-3", "mujhe thoda khaana chahiye", "எனக்கு கொஞ்சம் சாப்பாடு வேண்டும்", "I need a little food.", "chahiye", "mujhe + amount + thing + chahiye", "thoda softens a request: a little.", "Which word signals a small amount?", ["thoda", "mujhe", "khaana", "chahiye"], "thoda", .anchor, .anchors),
            prompt("d3-4", "tumne chai pi?", "நீ தேநீர் குடித்தாயா?", "Did you drink tea?", "peena", "tumne + thing + pi", "pi is a short past sound for peena.", "Is this about past or future?", ["Past", "Future", "Present action", "A location"], "Past", .timeClue, .gist)
        ], roleplay("day3-cafe", "At a cafe", "A friend asks what you want after work.", "kya logi?", "என்ன எடுத்துக்கொள்வாய்?", "What will you have?", ["Mujhe chai chahiye.", "Main ghar jaa rahi hoon.", "Darwaaza band hai.", "Kal aayega."], "Mujhe chai chahiye.", "எனக்கு தேநீர் வேண்டும்.", "I would like tea.", "chahiye is a high-value request frame; it is more useful than memorizing a full menu.")),
        makeDay(4, "Morning routine", "காலை வழக்கம்", "uthna, jaana, karna, abhi", "Follow a short routine by spotting the action and the now clue.", [
            prompt("d4-1", "abhi uth rahi hoon", "இப்போது எழுந்து கொண்டிருக்கிறேன்", "I am getting up now.", "uthna", "abhi + action rahi hoon", "abhi means now; rahi hoon marks a current action for a female speaker.", "When is this happening?", ["Now", "Yesterday", "Tomorrow", "Never"], "Now", .timeClue, .gist),
            prompt("d4-2", "main nahaane jaa rahi hoon", "நான் குளிக்கச் செல்கிறேன்", "I am going to bathe.", "jaana", "main + action + jaa rahi hoon", "jaa rahi hoon tells you the speaker is leaving toward an action.", "Which verb family carries the movement?", ["jaana", "aana", "bolna", "lena"], "jaana", .anchor, .verbFamilies),
            prompt("d4-3", "nashta kar liya?", "காலை உணவு சாப்பிட்டுவிட்டாயா?", "Did you have breakfast?", "karna", "thing + kar liya", "kar liya often means completed / got done.", "What is being checked?", ["Breakfast is done", "A trip is planned", "The door is open", "A message arrived"], "Breakfast is done", .meaning, .gist),
            prompt("d4-4", "aaj kaam karna hai", "இன்று வேலை செய்ய வேண்டும்", "I have to work today.", "karna", "aaj + kaam + karna hai", "aaj means today and karna hai carries a plan or need.", "What must happen today?", ["Work", "Travel", "Eat", "Call"], "Work", .meaning, .response)
        ], roleplay("day4-morning", "Before work", "Your friend asks if you are ready to leave.", "abhi nikalogi?", "இப்போது கிளம்புவாயா?", "Will you leave now?", ["Haan, bas nikal rahi hoon.", "Maine khaana khaaya.", "Mujhe paani chahiye.", "Woh room mein hai."], "Haan, bas nikal rahi hoon.", "ஆம், இப்போது கிளம்புகிறேன்.", "Yes, I am just leaving.", "bas means just / about to; it makes the reply sound natural.")),
        makeDay(5, "People around you", "உங்களைச் சுற்றியவர்கள்", "mummy, papa, dost, woh, sab", "Track who did the action when family and friends enter the sentence.", [
            prompt("d5-1", "woh dost ke saath gaya", "அவர் நண்பருடன் சென்றார்", "They went with a friend.", "jaana", "woh + person + ke saath + gaya", "gaya is a common past form in the go family.", "Who went with the friend?", ["They / he", "I", "You", "Nobody"], "They / he", .meaning, .gist),
            prompt("d5-2", "mummy ghar par hai", "அம்மா வீட்டில் இருக்கிறார்", "Mom is at home.", "hona", "person + place + par hai", "par means at / on a place.", "Where is mom?", ["At home", "At work", "Outside", "On the way"], "At home", .anchor, .anchors),
            prompt("d5-3", "papa ne phone kiya", "அப்பா தொலைபேசியில் அழைத்தார்", "Dad called.", "karna", "papa ne + phone kiya", "kiya is the past form learners will hear with many actions.", "What happened?", ["Dad called", "Dad came tomorrow", "Dad needs tea", "Dad is outside"], "Dad called", .meaning, .verbFamilies),
            prompt("d5-4", "sab log aa rahe hain", "எல்லோரும் வந்து கொண்டிருக்கிறார்கள்", "Everyone is coming.", "aana", "sab + aa rahe hain", "rahe hain signals a group action happening now.", "What are everyone doing?", ["Coming", "Going", "Eating", "Waiting"], "Coming", .timeClue, .gist)
        ], roleplay("day5-family", "Family call", "A family member asks if your friend has arrived.", "tumhara dost aaya?", "உன் நண்பர் வந்தாரா?", "Did your friend arrive?", ["Haan, abhi aaya hai.", "Kal office jaana hai.", "Mujhe chai chahiye.", "Main baahar jaa rahi hoon."], "Haan, abhi aaya hai.", "ஆம், இப்போது வந்துவிட்டார்.", "Yes, they just arrived.", "aaya is the past sound for aana; abhi tells you it was just now.")),
        makeDay(6, "Office and everyday work", "அலுவலகம் மற்றும் வேலை", "kaam, office, meeting, bhejna", "Understand the rough point of a normal work update.", [
            prompt("d6-1", "office mein meeting hai", "அலுவலகத்தில் கூட்டம் இருக்கிறது", "There is a meeting at the office.", "office", "place + mein + event hai", "mein means in / at; the place often comes before the event.", "What is at the office?", ["A meeting", "A train", "Dinner", "A friend"], "A meeting", .meaning, .anchors),
            prompt("d6-2", "message bhejna hai", "செய்தி அனுப்ப வேண்டும்", "I have to send a message.", "bhejna", "thing + bhejna hai", "The hai frame can carry an obligation without saying I.", "What needs to happen?", ["Send a message", "Read a book", "Buy food", "Go home"], "Send a message", .meaning, .response),
            prompt("d6-3", "main kaam kar rahi hoon", "நான் வேலை செய்து கொண்டிருக்கிறேன்", "I am working.", "karna", "main + kaam kar rahi hoon", "kaam is work; kar rahi hoon means doing now.", "Which anchor means work?", ["kaam", "kal", "ghar", "paani"], "kaam", .anchor, .anchors),
            prompt("d6-4", "woh file le gaya", "அவர் கோப்பை எடுத்துச் சென்றார்", "They took the file away.", "lena", "woh + thing + le gaya", "le gaya combines take + went away; hear the le- sound.", "Which action is closest?", ["Took away", "Gave back", "Opened", "Spoke"], "Took away", .meaning, .verbFamilies)
        ], roleplay("day6-office", "A work update", "A teammate asks whether the message has been sent.", "message bheja?", "செய்தி அனுப்பிவிட்டாயா?", "Did you send the message?", ["Haan, bhej diya.", "Main ghar aa rahi hoon.", "Mujhe paani chahiye.", "Kal movie dekhenge."], "Haan, bhej diya.", "ஆம், அனுப்பிவிட்டேன்.", "Yes, I sent it.", "diya is a useful completed-action sound; it appears with many everyday verbs.")),
        makeDay(7, "Week 1: anchor checkpoint", "முதல் வார சோதனை", "mixed home, food, people, work", "Use anchors first: identify the action, place, and time before worrying about every word.", [
            prompt("d7-1", "kal dost ke ghar jaana hai", "நாளை நண்பரின் வீட்டிற்குச் செல்ல வேண்டும்", "I have to go to my friend's house tomorrow.", "jaana", "kal + place + jaana hai", "Place plus jaana is enough to catch this plan.", "Which plan is correct?", ["Go to a friend's house tomorrow", "Eat at the office now", "Come home yesterday", "Call dad later"], "Go to a friend's house tomorrow", .meaning, .gist),
            prompt("d7-2", "maine chai pi aur kaam kiya", "நான் தேநீர் குடித்து வேலை செய்தேன்", "I drank tea and worked.", "karna", "maine + past action + aur + past action", "aur means and; it links two completed actions.", "What is the time frame?", ["Past", "Now", "Future", "Question only"], "Past", .timeClue, .gist),
            prompt("d7-3", "woh kya bol raha hai?", "அவர் என்ன பேசுகிறார்?", "What is he saying?", "bolna", "woh + kya + bol raha hai", "bol means say/speak; raha hai signals an action in progress.", "Which verb family should you choose?", ["bolna", "peena", "lena", "jaana"], "bolna", .anchor, .verbFamilies),
            prompt("d7-4", "mujhe ghar jaana hai", "எனக்கு வீட்டிற்குச் செல்ல வேண்டும்", "I need to go home.", "jaana", "mujhe + place + jaana hai", "This is a high-frequency need/intent frame.", "What does the speaker need to do?", ["Go home", "Drink tea", "Send a file", "Open the door"], "Go home", .reply, .response)
        ], roleplay("day7-checkpoint", "Quick check-in", "Your friend asks what you need to do next.", "ab kya karna hai?", "இப்போது என்ன செய்ய வேண்டும்?", "What do you have to do now?", ["Mujhe ghar jaana hai.", "Kal papa aaye.", "Darwaaza band hai.", "Maine chai pi."], "Mujhe ghar jaana hai.", "நான் வீட்டிற்குச் செல்ல வேண்டும்.", "I need to go home.", "A useful response can be a complete intent frame even when the question is fast.")),
        makeDay(8, "Time words", "நேரச் சொற்கள்", "aaj, kal, abhi, baad mein", "Use time words to orient a sentence before decoding the verb.", [
            prompt("d8-1", "aaj movie dekhna hai", "இன்று படம் பார்க்க வேண்டும்", "I have to watch a movie today.", "dekhna", "aaj + movie + dekhna hai", "aaj means today; the rest is a plan.", "When is the movie plan?", ["Today", "Yesterday", "Right now only", "Next month"], "Today", .timeClue, .anchors),
            prompt("d8-2", "kal aayega", "அவர் நாளை வருவார்", "He will come tomorrow.", "aana", "kal + aayega", "aayega is future for the come family.", "What is the time clue?", ["Future", "Past", "Present", "A request"], "Future", .timeClue, .gist),
            prompt("d8-3", "abhi nahi, baad mein", "இப்போது இல்லை, பிறகு", "Not now, later.", "baad mein", "abhi nahi + baad mein", "baad mein is a very reusable later marker.", "When should it happen?", ["Later", "Yesterday", "Now", "Never"], "Later", .anchor, .anchors),
            prompt("d8-4", "maine kal dekha", "நான் நேற்று பார்த்தேன்", "I saw it yesterday.", "dekhna", "maine + kal + dekha", "kal can mean yesterday or tomorrow; the verb form supplies the clue.", "What does the past form tell you here?", ["Saw yesterday", "Will see tomorrow", "Is seeing now", "Must watch"], "Saw yesterday", .meaning, .gist)
        ], roleplay("day8-time", "Making a plan", "A friend asks whether to meet today or later.", "aaj milna hai?", "இன்று சந்திக்க வேண்டுமா?", "Should we meet today?", ["Nahi, baad mein milte hain.", "Maine phone liya.", "Woh office mein hai.", "Khaana kha rahi hoon."], "Nahi, baad mein milte hain.", "இல்லை, பிறகு சந்திப்போம்.", "No, let's meet later.", "Time markers are your first filter: aaj, kal, abhi, baad mein.")),
        makeDay(9, "Getting around", "பயணம் மற்றும் போக்குவரத்து", "auto, bus, train, station, pahunchna", "Follow a simple travel update and notice arrival versus departure.", [
            prompt("d9-1", "auto se office jaa rahi hoon", "ஆட்டோவில் அலுவலகம் செல்கிறேன்", "I am going to the office by auto.", "jaana", "transport se + place + jaa rahi hoon", "se can mean by / via in travel contexts.", "How is the speaker travelling?", ["By auto", "By train", "On foot", "By flight"], "By auto", .anchor, .anchors),
            prompt("d9-2", "train aa gayi", "ரயில் வந்து விட்டது", "The train has arrived.", "aana", "train + aa gayi", "aa gayi is a completed feminine/inanimate arrival sound.", "What happened to the train?", ["It arrived", "It left", "It is delayed tomorrow", "It is inside"], "It arrived", .meaning, .verbFamilies),
            prompt("d9-3", "station pahunch gaye", "நிலையத்தை அடைந்து விட்டோம்", "We reached the station.", "pahunchna", "place + pahunch gaye", "gaye can signal a completed movement with we/they.", "What is complete?", ["Reaching the station", "Buying a ticket", "Calling a friend", "Eating food"], "Reaching the station", .timeClue, .gist),
            prompt("d9-4", "kitne baje nikloge?", "எத்தனை மணிக்கு கிளம்புவாய்?", "What time will you leave?", "nikalna", "kitne baje + future question", "kitne baje asks at what time.", "What is being asked?", ["Departure time", "Ticket price", "Destination", "Food choice"], "Departure time", .meaning, .response)
        ], roleplay("day9-travel", "On the way", "A friend asks if you have reached the station.", "station pahunchi?", "நிலையத்தை அடைந்தாயா?", "Did you reach the station?", ["Haan, abhi pahunchi.", "Kal aayega.", "Mujhe chai chahiye.", "Woh file le gaya."], "Haan, abhi pahunchi.", "ஆம், இப்போது அடைந்தேன்.", "Yes, I just reached it.", "pahunch- is a useful travel anchor; abhi makes the timing immediate.")),
        makeDay(10, "Shopping talk", "கடை உரையாடல்", "lena, dena, paise, kitna, chahiye", "Ask for an item, understand a price question, and respond simply.", [
            prompt("d10-1", "yeh lena hai", "இதை எடுக்க வேண்டும்", "I want / need to take this.", "lena", "yeh + lena hai", "lena means take / get; context decides the exact English.", "What action is planned?", ["Take / get this", "Give this away", "Watch this", "Eat this"], "Take / get this", .meaning, .verbFamilies),
            prompt("d10-2", "kitne paise hue?", "எவ்வளவு பணம் ஆனது?", "How much money is it?", "hona", "kitne paise + hue", "hue asks what the amount came to.", "What does the question ask?", ["The price", "The time", "The location", "The size"], "The price", .anchor, .response),
            prompt("d10-3", "mujhe yeh nahi chahiye", "எனக்கு இது வேண்டாம்", "I do not want this.", "chahiye", "mujhe + thing + nahi chahiye", "nahi makes the request negative.", "Does the speaker want it?", ["No", "Yes", "Maybe tomorrow", "Already bought it"], "No", .meaning, .gist),
            prompt("d10-4", "paise de do", "பணத்தை கொடுத்து விடுங்கள்", "Please give the money.", "dena", "thing + de do", "de do is a direct but common request to give something.", "Which verb means give?", ["dena", "lena", "jaana", "bolna"], "dena", .anchor, .verbFamilies)
        ], roleplay("day10-shop", "At a shop", "The seller asks if you want the blue bag.", "yeh bag logi?", "இந்த பையை எடுத்துக்கொள்வாயா?", "Will you take this bag?", ["Haan, yeh lena hai.", "Main office jaa rahi hoon.", "Kal train aa gayi.", "Kya hua?"], "Haan, yeh lena hai.", "ஆம், இதை எடுத்துக்கொள்கிறேன்.", "Yes, I will take this.", "lena is the take/get family; chahiye is useful when you want to soften the request.")),
        makeDay(11, "Useful requests", "பயனுள்ள வேண்டுகோள்கள்", "please, thoda, sakte ho, dena", "Make and understand polite everyday requests without full grammar study.", [
            prompt("d11-1", "thoda ruk sakte ho?", "கொஞ்சம் காத்திருக்க முடியுமா?", "Can you wait a little?", "rukna", "thoda + action + sakte ho", "sakte ho frames a can-you request.", "What is the request?", ["Wait a little", "Speak loudly", "Come tomorrow", "Give water"], "Wait a little", .reply, .response),
            prompt("d11-2", "paani de do please", "தண்ணீர் கொடுங்கள், தயவுசெய்து", "Please give me water.", "dena", "thing + de do + please", "please can sit naturally at the end of a request.", "What should the listener give?", ["Water", "Tea", "The phone", "A ticket"], "Water", .meaning, .anchors),
            prompt("d11-3", "ek minute ruko", "ஒரு நிமிடம் காத்திரு", "Wait one minute.", "rukna", "ek minute + ruko", "Short imperative phrases are common in fast speech.", "How long should they wait?", ["One minute", "Later", "An hour", "Tomorrow"], "One minute", .anchor, .gist),
            prompt("d11-4", "mujhe help chahiye", "எனக்கு உதவி வேண்டும்", "I need help.", "chahiye", "mujhe + help + chahiye", "Hinglish often uses English nouns inside Hindi frames.", "What does the speaker need?", ["Help", "Food", "A ride", "A message"], "Help", .meaning, .response)
        ], roleplay("day11-help", "A small favor", "You are carrying bags and ask for help.", "kuch help chahiye?", "ஏதாவது உதவி வேண்டுமா?", "Do you need some help?", ["Haan, yeh le lo please.", "Kal office jaana hai.", "Woh baahar gaya.", "Maine chai pi."], "Haan, yeh le lo please.", "ஆம், இதை எடுத்துக் கொள்ளுங்கள்.", "Yes, please take this.", "A natural reply can be short; le lo means take this / take it.")),
        makeDay(12, "Plans and invitations", "திட்டங்கள் மற்றும் அழைப்புகள்", "milna, aana, jaana, phir, shaam", "Understand invitations and whether the plan is fixed, happening, or still a question.", [
            prompt("d12-1", "shaam ko milte hain", "மாலை சந்திப்போம்", "Let's meet in the evening.", "milna", "time + milte hain", "milte hain is a friendly suggestion for meeting.", "What is the suggestion?", ["Meet in the evening", "Go in the morning", "Eat now", "Call tomorrow"], "Meet in the evening", .reply, .response),
            prompt("d12-2", "tum kal aaoge?", "நீ நாளை வருவாயா?", "Will you come tomorrow?", "aana", "tum + kal + aaoge", "aaoge is future with tum.", "Is this a plan or a question?", ["A future question", "A past report", "A present action", "A request for food"], "A future question", .timeClue, .gist),
            prompt("d12-3", "phir movie dekhte hain", "பிறகு படம் பார்ப்போம்", "Then let's watch a movie.", "dekhna", "phir + action + te hain", "phir means then / after that.", "What does phir add?", ["Then / after that", "Yesterday", "Maybe not", "Inside"], "Then / after that", .anchor, .anchors),
            prompt("d12-4", "main nahi aa paungi", "என்னால் வர முடியாது", "I will not be able to come.", "aana", "main + nahi + aa paungi", "nahi makes the future plan negative; paungi is ability/possibility.", "Can the speaker come?", ["No", "Yes now", "Already came", "Only to eat"], "No", .meaning, .gist)
        ], roleplay("day12-invite", "Making a plan", "A friend suggests meeting after work.", "shaam ko free ho?", "மாலை நேரம் காலியாக இருக்கிறாயா?", "Are you free in the evening?", ["Haan, milte hain.", "Maine phone liya.", "Paani de do.", "Woh ghar mein hai."], "Haan, milte hain.", "ஆம், சந்திப்போம்.", "Yes, let's meet.", "Milte hain is a ready-made social reply worth recognizing and using.")),
        makeDay(13, "Feelings and energy", "உணர்வுகள் மற்றும் சோர்வு", "thakna, achha, bura, mood, lagna", "Catch simple feeling statements and respond with empathy.", [
            prompt("d13-1", "aaj bahut thak gayi hoon", "இன்று மிகவும் சோர்வாக இருக்கிறேன்", "I am very tired today.", "thakna", "aaj + bahut + thak gayi hoon", "bahut means very / a lot; gayi hoon can mark a state reached.", "How does the speaker feel?", ["Very tired", "Very hungry", "Very late", "Very excited"], "Very tired", .meaning, .gist),
            prompt("d13-2", "mood theek nahi hai", "மனநிலை சரியாக இல்லை", "I am not in a good mood.", "hona", "mood + theek nahi hai", "theek means okay; nahi flips the meaning.", "Is the mood okay?", ["No", "Yes", "Unknown", "It is tomorrow"], "No", .meaning, .anchors),
            prompt("d13-3", "aaj achha lag raha hai", "இன்று நன்றாக உணர்கிறேன்", "I am feeling good today.", "lagna", "aaj + achha lag raha hai", "lag raha hai is a common feeling/state frame.", "Which feeling is closest?", ["Feeling good", "Feeling lost", "Feeling sleepy", "Feeling angry"], "Feeling good", .timeClue, .gist),
            prompt("d13-4", "thoda rest karna hai", "கொஞ்சம் ஓய்வெடுக்க வேண்டும்", "I need to rest a little.", "karna", "thoda + rest + karna hai", "Rest is often used as Hinglish inside a Hindi frame.", "What does the speaker need?", ["A little rest", "A ride", "A ticket", "A message"], "A little rest", .reply, .response)
        ], roleplay("day13-care", "Checking in", "A friend notices you sound tired.", "sab theek hai?", "எல்லாம் சரியாக இருக்கிறதா?", "Is everything okay?", ["Haan, bas thak gayi hoon.", "Kal train aa gayi.", "Paani de do.", "Woh office mein hai."], "Haan, bas thak gayi hoon.", "ஆம், சற்று சோர்வாக இருக்கிறேன்.", "Yes, I am just tired.", "bas can soften a status update: just tired, nothing dramatic.")),
        makeDay(14, "Week 2: errands checkpoint", "இரண்டாம் வார சோதனை", "time + request + plan + feeling", "Follow a short everyday exchange that moves from a question to a plan.", [
            prompt("d14-1", "aaj office jaana hai, phir ghar aana hai", "இன்று அலுவலகம் செல்ல வேண்டும், பிறகு வீட்டிற்கு வர வேண்டும்", "I have to go to the office today, then come home.", "jaana", "aaj + place + jaana hai + phir + ghar aana hai", "Two intent frames can be chained with phir.", "What comes after the office?", ["Come home", "Go shopping", "Drink tea", "Call a friend"], "Come home", .meaning, .gist),
            prompt("d14-2", "tumne message bheja?", "நீ செய்தி அனுப்பினாயா?", "Did you send the message?", "bhejna", "tumne + thing + bheja", "ne plus a past-looking verb often marks a completed action.", "What is being checked?", ["A sent message", "A future trip", "A current mood", "A door"], "A sent message", .timeClue, .gist),
            prompt("d14-3", "mujhe thoda time chahiye", "எனக்கு கொஞ்சம் நேரம் வேண்டும்", "I need a little time.", "chahiye", "mujhe + amount + time + chahiye", "time is a common English noun in Hindi conversations.", "What is needed?", ["A little time", "A little food", "A little money", "A little water"], "A little time", .anchor, .anchors),
            prompt("d14-4", "baad mein kar lenge", "பிறகு செய்து விடலாம்", "We can do it later.", "karna", "baad mein + kar lenge", "lenge signals a future possibility/plan with we.", "When will it happen?", ["Later", "Already", "Now", "Never"], "Later", .reply, .response)
        ], roleplay("day14-checkpoint", "Busy day", "A friend asks whether you can talk now.", "abhi baat kar sakti ho?", "இப்போது பேச முடியுமா?", "Can you talk now?", ["Nahi, baad mein baat karte hain.", "Maine khaana khaaya.", "Woh station pahunch gaya.", "Mujhe chai chahiye."], "Nahi, baad mein baat karte hain.", "இல்லை, பிறகு பேசுவோம்.", "No, we can talk later.", "The goal is to follow the decision in context, not translate every filler word.")),
        makeDay(15, "Past actions", "கடந்த செயல்கள்", "kiya, gaya, aaya, liya", "Recognize a completed action even when the verb changes shape.", [
            prompt("d15-1", "maine kaam kiya", "நான் வேலை செய்தேன்", "I worked / did the work.", "karna", "maine + kaam kiya", "kiya is the past sound to attach to many familiar actions.", "What happened?", ["The work was done", "The work is starting", "The work is tomorrow", "The work was requested"], "The work was done", .meaning, .verbFamilies),
            prompt("d15-2", "woh kal ghar gaya", "அவர் நேற்று வீட்டிற்குச் சென்றார்", "They went home yesterday.", "jaana", "woh + kal + ghar gaya", "gaya belongs to the jaana family even though it sounds different.", "Which family is gaya?", ["jaana / to go", "aana / to come", "peena / to drink", "bolna / to speak"], "jaana / to go", .anchor, .verbFamilies),
            prompt("d15-3", "main late aayi", "நான் தாமதமாக வந்தேன்", "I arrived late.", "aana", "main + late aayi", "aayi is a common past form for a female speaker in the come family.", "Who arrived late?", ["The speaker", "A friend", "The train", "Nobody"], "The speaker", .meaning, .gist),
            prompt("d15-4", "phone liya?", "தொலைபேசியை எடுத்தாயா?", "Did you take the phone?", "lena", "thing + liya", "liya is a common past form of lena.", "Which time is this?", ["Past / completed", "Future", "Present ongoing", "Need"], "Past / completed", .timeClue, .gist)
        ], roleplay("day15-past", "After an errand", "Someone asks whether you bought the item.", "saamaan liya?", "பொருளை எடுத்தாயா?", "Did you get the item?", ["Haan, le liya.", "Kal jaaungi.", "Mujhe rest chahiye.", "Woh aa raha hai."], "Haan, le liya.", "ஆம், எடுத்துவிட்டேன்.", "Yes, I got it.", "le liya is a compact completion frame: took/got it.")),
        makeDay(16, "Happening right now", "இப்போது நடப்பது", "raha, rahi, rahe, abhi", "Hear the action that is in progress and the person doing it.", [
            prompt("d16-1", "woh khaana kha raha hai", "அவர் சாப்பிட்டு கொண்டிருக்கிறார்", "He is eating.", "khaana", "woh + kha raha hai", "raha hai marks a masculine singular current action.", "What is he doing?", ["Eating", "Drinking", "Going", "Speaking"], "Eating", .meaning, .gist),
            prompt("d16-2", "main message likh rahi hoon", "நான் செய்தி எழுதிக் கொண்டிருக்கிறேன்", "I am writing a message.", "likhna", "main + action rahi hoon", "rahi hoon is the current-action clue for the speaker here.", "Which time clue did you hear?", ["Happening now", "Past", "Future", "A request"], "Happening now", .timeClue, .gist),
            prompt("d16-3", "woh log baat kar rahe hain", "அவர்கள் பேசிக் கொண்டிருக்கிறார்கள்", "They are talking.", "bolna", "woh log + baat kar rahe hain", "rahe hain points to a plural group action now.", "Who is talking?", ["They", "I", "You", "Nobody"], "They", .anchor, .response),
            prompt("d16-4", "kya dekh rahi ho?", "எதைப் பார்த்துக் கொண்டிருக்கிறாய்?", "What are you watching?", "dekhna", "kya + dekh rahi ho", "The question asks about a current action.", "What is being asked?", ["What you are watching", "Where you went", "What you bought", "When you will come"], "What you are watching", .meaning, .gist)
        ], roleplay("day16-now", "A live update", "Your friend asks what you are doing right now.", "kya kar rahi ho?", "என்ன செய்து கொண்டிருக்கிறாய்?", "What are you doing?", ["Main khaana bana rahi hoon.", "Kal office gayi.", "Mujhe paise chahiye.", "Woh ghar aa gaya."], "Main khaana bana rahi hoon.", "நான் சாப்பாடு செய்து கொண்டிருக்கிறேன்.", "I am cooking.", "The rahi ho frame tells you the action is live; the anchor supplies the action.")),
        makeDay(17, "Future and intention", "எதிர்காலம் மற்றும் நோக்கம்", "jaayega, aaungi, karenge, hoga", "Separate a future plan from a current action or a completed story.", [
            prompt("d17-1", "main kal aaungi", "நான் நாளை வருவேன்", "I will come tomorrow.", "aana", "main + kal + aaungi", "aaungi is a first-person-female future form in the come family.", "When will the speaker come?", ["Tomorrow", "Yesterday", "Now", "Later today only"], "Tomorrow", .timeClue, .verbFamilies),
            prompt("d17-2", "woh shaam ko karega", "அவர் மாலையில் செய்வார்", "He will do it in the evening.", "karna", "woh + time + karega", "karega is future for the do family.", "Is the action done yet?", ["No, it is future", "Yes, yesterday", "It is happening now", "It is a request"], "No, it is future", .meaning, .gist),
            prompt("d17-3", "kal milenge", "நாளை சந்திப்போம்", "We will meet tomorrow.", "milna", "kal + milenge", "milenge is a useful we-future social phrase.", "What is planned?", ["Meet tomorrow", "Eat now", "Leave yesterday", "Send a message"], "Meet tomorrow", .reply, .response),
            prompt("d17-4", "sab theek hoga", "எல்லாம் சரியாக இருக்கும்", "Everything will be okay.", "hona", "sab theek hoga", "hoga is a future form of hona.", "Which word carries the future?", ["hoga", "theek", "sab", "hai"], "hoga", .anchor, .anchors)
        ], roleplay("day17-future", "Tomorrow's plan", "A friend checks whether you will join tomorrow.", "kal aaogi?", "நாளை வருவாயா?", "Will you come tomorrow?", ["Haan, aaungi.", "Maine phone liya.", "Abhi kha rahi hoon.", "Woh ghar gaya."], "Haan, aaungi.", "ஆம், வருவேன்.", "Yes, I will come.", "Future endings vary; keep the time word and the verb family together.")),
        makeDay(18, "Questions that unlock context", "சூழலைத் திறக்கும் கேள்விகள்", "kya, kab, kahan, kyun, kaise", "Identify what kind of information a fast question is asking for.", [
            prompt("d18-1", "kahan jaa rahe ho?", "எங்கே செல்கிறாய்?", "Where are you going?", "jaana", "kahan + jaa rahe ho", "kahan asks where.", "What information is requested?", ["Place", "Time", "Reason", "Person"], "Place", .anchor, .response),
            prompt("d18-2", "kab aayega?", "எப்போது வருவார்?", "When will he come?", "aana", "kab + aayega", "kab asks when; aayega points to future come.", "What is being asked?", ["When", "Where", "Why", "How"], "When", .anchor, .anchors),
            prompt("d18-3", "kyun nahi kiya?", "ஏன் செய்யவில்லை?", "Why did you not do it?", "karna", "kyun + nahi + kiya", "kyun asks why; nahi negates the past action.", "What is the feeling of the question?", ["A reason for not doing it", "A place", "A future invitation", "A food order"], "A reason for not doing it", .meaning, .gist),
            prompt("d18-4", "kaise karna hai?", "எப்படிச் செய்ய வேண்டும்?", "How should it be done?", "karna", "kaise + karna hai", "kaise asks how; the hai frame signals an instruction/need.", "What is requested?", ["A method", "A time", "A person", "A location"], "A method", .reply, .response)
        ], roleplay("day18-questions", "Clarifying", "You did not hear the plan and ask for the location.", "kahan milna hai?", "எங்கே சந்திக்க வேண்டும்?", "Where should we meet?", ["Station ke paas.", "Kal aaungi.", "Mujhe paani chahiye.", "Maine kaam kiya."], "Station ke paas.", "நிலையத்தின் அருகில்.", "Near the station.", "A place answer can be short; paas means near and often comes after the place.")),
        makeDay(19, "Negatives and boundaries", "மறுப்பு மற்றும் எல்லைகள்", "nahi, mat, abhi nahi, nahi pata", "Understand simple no / not yet / do not commands in real conversation.", [
            prompt("d19-1", "mujhe nahi pata", "எனக்குத் தெரியாது", "I do not know.", "pata", "mujhe + nahi + pata", "pata is a useful knowledge anchor even without grammar labels.", "What does the speaker know?", ["They do not know", "They know now", "They will know tomorrow", "They want food"], "They do not know", .meaning, .gist),
            prompt("d19-2", "abhi mat jao", "இப்போது செல்லாதே", "Do not go now.", "jaana", "abhi + mat + jao", "mat makes a direct do-not command.", "What should the listener do?", ["Stay for now", "Go immediately", "Eat now", "Call later"], "Stay for now", .reply, .response),
            prompt("d19-3", "nahi, kal karungi", "இல்லை, நாளை செய்வேன்", "No, I will do it tomorrow.", "karna", "nahi + kal + karungi", "A short nahi can answer the previous question before the future plan.", "When will it be done?", ["Tomorrow", "Now", "Yesterday", "Never"], "Tomorrow", .timeClue, .gist),
            prompt("d19-4", "yeh nahi lena", "இதை எடுக்க வேண்டாம்", "Do not take this.", "lena", "thing + nahi lena", "The frame is a boundary about what not to take.", "Which action is blocked?", ["Taking this", "Giving this", "Seeing this", "Saying this"], "Taking this", .anchor, .verbFamilies)
        ], roleplay("day19-boundary", "A small boundary", "A friend offers a spicy dish you do not want.", "yeh khaogi?", "இதைச் சாப்பிடுவாயா?", "Will you eat this?", ["Nahi, yeh nahi chahiye.", "Haan, kal aaungi.", "Woh ghar mein hai.", "Maine message bheja."], "Nahi, yeh nahi chahiye.", "இல்லை, இது வேண்டாம்.", "No, I do not want this.", "nahi chahiye is a practical, polite boundary in everyday speech.")),
        makeDay(20, "Connectors and messy speech", "இணைப்புச் சொற்கள்", "aur, lekin, kyunki, phir, bas", "Keep the main point while fillers and connectors make the sentence longer.", [
            prompt("d20-1", "main aaungi lekin thoda late", "நான் வருவேன், ஆனால் கொஞ்சம் தாமதமாக", "I will come, but a little late.", "aana", "main aaungi + lekin + late", "lekin means but and protects the main contrast.", "What is the caveat?", ["The speaker will be late", "The speaker will not come", "The speaker came yesterday", "The speaker needs food"], "The speaker will be late", .meaning, .gist),
            prompt("d20-2", "pehle kaam, phir movie", "முதலில் வேலை, பிறகு படம்", "Work first, then a movie.", "karna", "pehle + action, phir + action", "pehle means first; phir means then.", "What comes first?", ["Work", "Movie", "Dinner", "Travel"], "Work", .anchor, .anchors),
            prompt("d20-3", "main nahi aa rahi kyunki thak gayi hoon", "நான் வரவில்லை, ஏனெனில் சோர்வாக இருக்கிறேன்", "I am not coming because I am tired.", "aana", "nahi + action + kyunki + reason", "kyunki introduces the reason.", "Why is the speaker not coming?", ["They are tired", "They are at work", "They need water", "They are travelling"], "They are tired", .meaning, .gist),
            prompt("d20-4", "bas ek minute", "ஒரு நிமிடம் மட்டும்", "Just one minute.", "bas", "bas + amount", "bas can mean just / that's all and is common in quick replies.", "How long?", ["Just one minute", "A long time", "Tomorrow", "Not at all"], "Just one minute", .reply, .response)
        ], roleplay("day20-connectors", "Changing a plan", "You need to explain why you are late.", "itni der kyun?", "இவ்வளவு நேரம் ஏன்?", "Why so late?", ["Traffic tha, isliye late.", "Mujhe chai chahiye.", "Kal movie dekhi.", "Woh paani de raha hai."], "Traffic tha, isliye late.", "போக்குவரத்து இருந்தது, அதனால் தாமதம்.", "There was traffic, so I am late.", "isliye means so / therefore; keep the reason and result together.")),
        makeDay(21, "Week 3: time and tense checkpoint", "மூன்றாம் வார சோதனை", "past vs now vs future in one exchange", "Track when actions happen while the words get shorter and faster.", [
            prompt("d21-1", "kal gayi thi, aaj ghar par hoon", "நேற்று சென்றிருந்தேன், இன்று வீட்டில் இருக்கிறேன்", "I went yesterday; today I am at home.", "jaana", "past + aaj + present", "The time words do much of the work here.", "Where is the speaker today?", ["At home", "At the office", "At a cafe", "On a train"], "At home", .meaning, .gist),
            prompt("d21-2", "abhi kha rahi hoon, baad mein bolungi", "இப்போது சாப்பிடுகிறேன், பிறகு பேசுவேன்", "I am eating now; I will talk later.", "khaana", "abhi + current, baad mein + future", "Two time frames can be chained in one natural line.", "When will she talk?", ["Later", "Now", "Yesterday", "Never"], "Later", .timeClue, .gist),
            prompt("d21-3", "woh kal aayega, phir dekhenge", "அவர் நாளை வருவார், பிறகு பார்ப்போம்", "He will come tomorrow; then we will see.", "aana", "future + phir + future", "dekhenge can mean we will see / decide then.", "What is the rough plan?", ["Wait for him, then decide", "Eat now", "Go home yesterday", "Send a message"], "Wait for him, then decide", .meaning, .response),
            prompt("d21-4", "maine kya kiya?", "நான் என்ன செய்தேன்?", "What did I do?", "karna", "maine + kya + kiya", "The repeated kya/kiya sounds still carry a past question.", "Which time frame?", ["Past", "Present", "Future", "Location"], "Past", .anchor, .verbFamilies)
        ], roleplay("day21-checkpoint", "Three time frames", "A friend asks what you are doing and what you will do later.", "abhi kya kar rahi ho, baad mein?", "இப்போது என்ன செய்கிறாய், பிறகு?", "What are you doing now, and later?", ["Abhi kha rahi hoon, baad mein bolungi.", "Kal office gayi.", "Mujhe paise chahiye.", "Darwaaza band karo."], "Abhi kha rahi hoon, baad mein bolungi.", "இப்போது சாப்பிடுகிறேன், பிறகு பேசுவேன்.", "I am eating now; I will talk later.", "Use the time words as rails; they keep a fast sentence understandable.")),
        makeDay(22, "Phone and messages", "தொலைபேசி மற்றும் செய்திகள்", "call, phone, message, dekhna, bhejna", "Understand what happened on a phone and choose a natural follow-up.", [
            prompt("phone-liya", "phone liya?", "தொலைபேசியை எடுத்தாயா?", "Did you pick up the phone?", "lena", "phone + liya", "A tiny phrase can be a complete check-in.", "What is being checked?", ["Whether the phone was picked up", "Whether tea was drunk", "Whether someone arrived", "Whether work is done"], "Whether the phone was picked up", .meaning, .anchors),
            prompt("message-dena", "usko message dena hai", "அவருக்கு செய்தி கொடுக்க வேண்டும்", "I have to message them.", "dena", "person + message + dena hai", "dena can mean give/send in a message context.", "Who gets the message?", ["That person", "The office", "The station", "Nobody"], "That person", .anchor, .verbFamilies),
            prompt("d22-3", "call kar lena", "அழைத்து விடு", "Do make the call / remember to call.", "karna", "call + kar lena", "kar lena is a light reminder to complete an action.", "What is the speaker asking?", ["Make a call", "Send money", "Come home", "Wait"], "Make a call", .reply, .response),
            prompt("d22-4", "video baad mein dekhungi", "வீடியோவை பிறகு பார்ப்பேன்", "I will watch the video later.", "dekhna", "thing + baad mein + dekhungi", "dekhungi is a first-person-female future form.", "When will she watch it?", ["Later", "Now", "Yesterday", "Never"], "Later", .timeClue, .gist)
        ], roleplay("day22-phone", "Missed call", "Your friend asks why you did not answer.", "call kyun nahi uthaya?", "அழைப்பை ஏன் எடுக்கவில்லை?", "Why did you not answer the call?", ["Phone silent tha, abhi dekha.", "Kal ghar jaaungi.", "Mujhe khaana chahiye.", "Woh aa raha hai."], "Phone silent tha, abhi dekha.", "தொலைபேசி அமைதியாக இருந்தது, இப்போதுதான் பார்த்தேன்.", "My phone was silent; I just saw it.", "abhi dekha gives a compact, believable reason in a phone exchange.")),
        makeDay(23, "Health and rest", "உடல்நலம் மற்றும் ஓய்வு", "dard, dawa, doctor, rest, theek", "Catch a simple health update and respond without needing medical vocabulary.", [
            prompt("d23-1", "sir dard kar raha hai", "தலை வலிக்கிறது", "My head hurts.", "karna", "body part + dard kar raha hai", "dard means pain; kar raha hai signals current discomfort.", "What is happening?", ["The head hurts", "The head is cold", "The head is outside", "The head will arrive"], "The head hurts", .meaning, .gist),
            prompt("d23-2", "doctor ke paas jaana hai", "மருத்துவரிடம் செல்ல வேண்டும்", "I have to go to the doctor.", "jaana", "person/place ke paas + jaana hai", "ke paas means to / near a person or place.", "Where does the speaker need to go?", ["To the doctor", "To the office", "To the station", "Home"], "To the doctor", .reply, .response),
            prompt("d23-3", "dawa le li?", "மருந்தை எடுத்தாயா?", "Did you take the medicine?", "lena", "thing + le li", "le li is a compact completed-action question.", "What should have been taken?", ["Medicine", "Water", "A phone", "A train"], "Medicine", .anchor, .anchors),
            prompt("d23-4", "ab theek hoon", "இப்போது நன்றாக இருக்கிறேன்", "I am okay now.", "hona", "ab + theek hoon", "ab means now; theek hoon is an easy status reply.", "How does the speaker feel now?", ["Okay", "Very tired", "Lost", "Late"], "Okay", .meaning, .gist)
        ], roleplay("day23-care", "Checking on someone", "You ask a friend if they are feeling better.", "ab kaisi ho?", "இப்போது எப்படி இருக்கிறாய்?", "How are you now?", ["Ab theek hoon, thanks.", "Kal office jaaungi.", "Phone liya?", "Mujhe chai chahiye."], "Ab theek hoon, thanks.", "இப்போது நன்றாக இருக்கிறேன், நன்றி.", "I am okay now, thanks.", "theek is a useful positive status; pair it with ab for now.")),
        makeDay(24, "Social invitations", "சமூக அழைப்புகள்", "aana, jaana, party, saath, chalo", "Join a social plan, decline kindly, and recognize a quick invitation.", [
            prompt("d24-1", "mere saath chalo", "என்னுடன் வாருங்கள்", "Come with me.", "aana", "mere saath + chalo", "chalo is a friendly invitation or prompt to go.", "What is the invitation?", ["Come along", "Wait here", "Eat later", "Call someone"], "Come along", .reply, .response),
            prompt("d24-2", "aaj party mein jaa rahe hain", "இன்று விருந்துக்குச் செல்கிறோம்", "We are going to a party today.", "jaana", "aaj + event mein + jaa rahe hain", "rahe hain tells you this is a group plan/action.", "Where are they going?", ["To a party", "To a doctor", "To the office", "Home"], "To a party", .meaning, .anchors),
            prompt("d24-3", "main nahi aa paungi, sorry", "என்னால் வர முடியாது, மன்னிக்கவும்", "I will not be able to come, sorry.", "aana", "nahi + aa paungi", "A kind refusal can be direct and short.", "What is the answer to the invitation?", ["Cannot come", "Will come now", "Already came", "Needs food"], "Cannot come", .meaning, .gist),
            prompt("d24-4", "sab log mil rahe hain", "எல்லோரும் சந்தித்து கொண்டிருக்கிறார்கள்", "Everyone is meeting up.", "milna", "sab log + mil rahe hain", "mil- is the meet family; rahe hain marks the group now.", "What are the people doing?", ["Meeting up", "Leaving", "Eating", "Sleeping"], "Meeting up", .timeClue, .verbFamilies)
        ], roleplay("day24-social", "A casual invite", "A friend asks if you are free to join a small gathering.", "aaj free ho?", "இன்று நேரம் இருக்கிறதா?", "Are you free today?", ["Haan, chalo.", "Maine dawa le li.", "Woh kal gaya.", "Mujhe paise chahiye."], "Haan, chalo.", "ஆம், போகலாம்.", "Yes, let's go.", "chalo is a compact social response; it often carries enthusiasm without extra grammar.")),
        makeDay(25, "Opinions and reactions", "கருத்துகள் மற்றும் எதிர்வினைகள்", "lagna, achha, pasand, sahi, lagta hai", "Recognize simple likes, opinions, and agreement in conversational Hindi/Hinglish.", [
            prompt("d25-1", "mujhe yeh movie pasand hai", "எனக்கு இந்த படம் பிடிக்கும்", "I like this movie.", "pasand", "mujhe + thing + pasand hai", "pasand hai is a high-value like frame.", "How does the speaker feel about the movie?", ["Likes it", "Dislikes it", "Has not seen it", "Must watch it"], "Likes it", .meaning, .gist),
            prompt("d25-2", "achha lag raha hai", "நன்றாக உணருகிறது", "It feels good.", "lagna", "achha + lag raha hai", "lag raha hai can describe a current impression.", "What is the reaction?", ["Feels good", "Feels late", "Feels empty", "Feels difficult"], "Feels good", .anchor, .anchors),
            prompt("d25-3", "sahi bol rahe ho", "நீ சரியாகச் சொல்கிறாய்", "You are saying the right thing.", "bolna", "sahi + bol rahe ho", "sahi means right/correct; bol rahe ho is speaking now.", "What is being praised?", ["The way someone is speaking", "Their travel", "Their food", "Their timing"], "The way someone is speaking", .meaning, .verbFamilies),
            prompt("d25-4", "lagta hai baarish hogi", "மழை பெய்யும் போலிருக்கிறது", "It seems it will rain.", "hona", "lagta hai + future", "lagta hai means it seems; hogi carries a future guess.", "What is the speaker predicting?", ["Rain", "A meeting", "A call", "A trip"], "Rain", .timeClue, .gist)
        ], roleplay("day25-reaction", "Sharing a reaction", "A friend asks if you enjoyed the movie.", "movie kaisi lagi?", "படம் எப்படி இருந்தது?", "How did you like the movie?", ["Achhi lagi.", "Kal aaungi.", "Mujhe rest chahiye.", "Woh office gaya."], "Achhi lagi.", "நன்றாக இருந்தது.", "I liked it.", "The word lagi/lagi may be all you catch; the positive achhi supplies the gist.")),
        makeDay(26, "Repair a misunderstanding", "புரியாததை சரிசெய்தல்", "samajhna, phir se, dheere, matlab", "Ask for repetition and keep the conversation moving when a phrase is missed.", [
            prompt("d26-1", "phir se bolna", "மீண்டும் சொல்லுங்கள்", "Say it again.", "bolna", "phir se + bolna", "phir se means again; it is a practical repair phrase.", "What is requested?", ["Say it again", "Go outside", "Wait tomorrow", "Give water"], "Say it again", .reply, .response),
            prompt("d26-2", "thoda dheere bolo", "கொஞ்சம் மெதுவாகப் பேசுங்கள்", "Speak a little slowly.", "bolna", "thoda + dheere + bolo", "dheere means slowly; bolo is a direct speak request.", "How should they speak?", ["More slowly", "More loudly", "Tomorrow", "Outside"], "More slowly", .meaning, .gist),
            prompt("d26-3", "samajh nahi aaya", "புரியவில்லை", "I did not understand.", "aana", "samajh nahi aaya", "aaya here is the arrived/understood result frame.", "What is the problem?", ["The meaning did not come through", "The person is late", "The food is missing", "The phone is off"], "The meaning did not come through", .meaning, .gist),
            prompt("d26-4", "matlab kya hai?", "அதன் அர்த்தம் என்ன?", "What does it mean?", "matlab", "matlab + kya hai", "matlab is a useful English-like Hindi anchor for meaning.", "What is being asked?", ["The meaning", "The time", "The price", "The place"], "The meaning", .anchor, .anchors)
        ], roleplay("day26-repair", "When speech is fast", "Your friend says something too quickly.", "samjha?", "புரிந்ததா?", "Did you understand?", ["Thoda dheere bolo please.", "Haan, kal gaya.", "Mujhe phone chahiye.", "Woh aa rahi hai."], "Thoda dheere bolo please.", "கொஞ்சம் மெதுவாகப் பேசுங்கள்.", "Please speak a little slowly.", "Repairing the conversation is a success skill; it keeps you in the exchange.")),
        makeDay(27, "Fast Hinglish gist", "வேகமான கலப்பு பேச்சு", "but, mood, scene, already, manage", "Catch the emotional or practical point in casual Hinglish.", [
            prompt("d27-1", "kal office jaana hai but mood nahi hai", "நாளை அலுவலகம் செல்ல வேண்டும், ஆனால் மனநிலை இல்லை", "I have to go to the office tomorrow, but I am not in the mood.", "jaana", "plan + but + feeling", "The second half changes the emotional point.", "Why might the speaker complain?", ["They have work but no mood", "They are going on holiday", "They need water", "They arrived early"], "They have work but no mood", .meaning, .gist),
            prompt("d27-2", "scene kya hai?", "நிலைமை என்ன?", "What is going on?", "hona", "scene + kya hai", "scene is a casual situation/context word.", "What does the speaker want?", ["The situation", "A ticket", "Food", "A location"], "The situation", .anchor, .response),
            prompt("d27-3", "already kar diya", "ஏற்கனவே செய்து விட்டேன்", "I already did it.", "karna", "already + kar diya", "already and diya make completion easy to catch.", "Is the task complete?", ["Yes, already", "No, tomorrow", "It is in progress", "It is a question"], "Yes, already", .timeClue, .gist),
            prompt("d27-4", "manage kar lenge", "சமாளித்து விடலாம்", "We will manage.", "karna", "manage + kar lenge", "Hinglish keeps practical English words inside Hindi endings.", "What is the attitude?", ["We can handle it", "We must leave", "We are confused", "We need food"], "We can handle it", .reply, .response)
        ], roleplay("day27-casual", "Casual complaint", "A friend says the plan is difficult; you reassure them.", "kaise hoga?", "எப்படிச் சாத்தியமாகும்?", "How will it work?", ["Manage kar lenge.", "Mujhe chai chahiye.", "Kal aayi thi.", "Woh ghar gaya."], "Manage kar lenge.", "சமாளித்து விடலாம்.", "We will manage.", "In casual speech, the English anchor plus a Hindi ending is often the fastest route to gist.")),
        makeDay(28, "A full errand", "முழு வேலைச் சுற்று", "go, get, ask, pay, return", "Follow a multi-step errand by holding onto the action chain.", [
            prompt("d28-1", "pehle market jaake sabzi lena hai", "முதலில் சந்தைக்குச் சென்று காய்கறி வாங்க வேண்டும்", "First I have to go to the market and get vegetables.", "lena", "pehle + place jaake + thing lena hai", "jaake means after going; lena is get/take.", "What is the first destination?", ["The market", "The office", "The station", "Home"], "The market", .meaning, .gist),
            prompt("d28-2", "paise deke ghar aaungi", "பணம் கொடுத்து வீட்டிற்கு வருவேன்", "After paying, I will come home.", "aana", "paise deke + ghar aaungi", "deke links an action before the next one.", "What happens after paying?", ["Come home", "Go to work", "Watch a movie", "Call a friend"], "Come home", .timeClue, .gist),
            prompt("d28-3", "sabzi mil gayi", "காய்கறி கிடைத்து விட்டது", "I found the vegetables.", "milna", "thing + mil gayi", "mil gayi means was found/received; it is a useful result phrase.", "What was found?", ["Vegetables", "A phone", "A ticket", "A message"], "Vegetables", .anchor, .anchors),
            prompt("d28-4", "ab ghar chalte hain", "இப்போது வீட்டிற்குச் செல்வோம்", "Now let's go home.", "jaana", "ab + ghar + chalte hain", "chalte hain is a natural group suggestion to leave/go.", "What is the next move?", ["Go home", "Buy food", "Wait", "Call"], "Go home", .reply, .response)
        ], roleplay("day28-errand", "After shopping", "You tell a friend the errand is done and you are returning.", "sab mil gaya?", "எல்லாம் கிடைத்ததா?", "Did you get everything?", ["Haan, sab mil gaya. Ab ghar chalte hain.", "Kal office jaana hai.", "Mujhe rest chahiye.", "Phone liya?"], "Haan, sab mil gaya. Ab ghar chalte hain.", "ஆம், எல்லாம் கிடைத்தது. இப்போது வீட்டிற்குச் செல்வோம்.", "Yes, got everything. Let's go home now.", "Hold on to result + next move; you can understand the exchange without every noun.")),
        makeDay(29, "Conversation rehearsal", "உரையாடல் பயிற்சி", "listen, repair, respond, continue", "Move from recognition to a short, useful back-and-forth.", [
            prompt("d29-1", "kahan thi? phone kyun nahi uthaya?", "எங்கே இருந்தாய்? தொலைபேசியை ஏன் எடுக்கவில்லை?", "Where were you? Why did you not answer the phone?", "lena", "past place + why + phone take", "Two questions may arrive together; catch the reason request first.", "What is the second question about?", ["The unanswered phone", "The dinner", "Tomorrow's trip", "The office"], "The unanswered phone", .meaning, .gist),
            prompt("d29-2", "main market mein thi, phone silent tha", "நான் சந்தையில் இருந்தேன், தொலைபேசி அமைதியாக இருந்தது", "I was in the market; the phone was silent.", "hona", "place + mein thi + reason/status", "thi is a past state form; silent is an easy anchor.", "Why did she miss the call?", ["The phone was silent", "She was asleep", "She was at work", "She had no water"], "The phone was silent", .meaning, .gist),
            prompt("d29-3", "theek hai, baad mein baat karte hain", "சரி, பிறகு பேசுவோம்", "Okay, we will talk later.", "bolna", "theek hai + baad mein baat karte hain", "A repair can end with a calm future suggestion.", "When will they talk?", ["Later", "Now", "Yesterday", "Never"], "Later", .timeClue, .response),
            prompt("d29-4", "haan, main message kar dungi", "ஆம், நான் செய்தி அனுப்பி விடுகிறேன்", "Yes, I will message you.", "karna", "main + message kar dungi", "kar dungi is a future promise to complete an action.", "What will the speaker do?", ["Send a message", "Come to the market", "Drink tea", "Take the phone"], "Send a message", .reply, .response)
        ], roleplay("day29-rehearsal", "A real catch-up", "A friend asks whether you can talk later after a missed call.", "baad mein baat karogi?", "பிறகு பேசுவாயா?", "Will you talk later?", ["Haan, message kar dena.", "Maine kal khaaya.", "Woh station mein hai.", "Mujhe paani chahiye."], "Haan, message kar dena.", "ஆம், செய்தி அனுப்பி விடு.", "Yes, send me a message.", "A useful conversation is a series of small successful turns, not a perfect translation.")),
        makeDay(30, "Final mission: follow the point", "இறுதி பயிற்சி: கருத்தைப் பின்தொடருங்கள்", "mixed everyday conversation", "Handle a predictable short exchange, repair once, and answer with your own useful line.", [
            prompt("d30-1", "aaj office ke baad ghar aaogi ya dost ke saath jaogi?", "இன்று அலுவலகத்திற்குப் பிறகு வீட்டிற்கு வருவாயா அல்லது நண்பருடன் செல்வாயா?", "After work today, will you come home or go with a friend?", "jaana", "choice question + after work", "ya means or; catch the two possible destinations.", "What two options are offered?", ["Home or go with a friend", "Tea or water", "Yesterday or tomorrow", "Phone or message"], "Home or go with a friend", .meaning, .gist),
            prompt("d30-2", "pehle ghar aaungi, phir dekhte hain", "முதலில் வீட்டிற்கு வருவேன், பிறகு பார்ப்போம்", "I will come home first, then we will see.", "aana", "pehle + future, phir + decision", "The reply keeps the first action clear and leaves the rest open.", "What will happen first?", ["Come home", "Go with a friend", "Eat at the office", "Call now"], "Come home", .timeClue, .gist),
            prompt("d30-3", "theek hai, mujhe message kar dena", "சரி, எனக்கு செய்தி அனுப்பி விடு", "Okay, send me a message.", "karna", "theek hai + message kar dena", "This is a natural way to close a plan.", "What should happen next?", ["Send a message", "Go to the station", "Drink tea", "Wait outside"], "Send a message", .reply, .response),
            prompt("d30-4", "samajh aaya?", "புரிந்ததா?", "Did that make sense?", "samajhna", "samajh + aaya", "A final check is a chance to use your repair skill honestly.", "What is the listener checking?", ["Whether it made sense", "Whether the food arrived", "Whether the phone rang", "Whether the train left"], "Whether it made sense", .anchor, .anchors)
        ], roleplay("day30-final", "The final mission", "A friend asks about your plan after work; choose a reply and keep the exchange moving.", "office ke baad kya plan hai?", "அலுவலகத்திற்குப் பிறகு என்ன திட்டம்?", "What is your plan after work?", ["Pehle ghar aaungi, phir dekhte hain.", "Mujhe dawa chahiye.", "Kal train aayi.", "Darwaaza band hai."], "Pehle ghar aaungi, phir dekhte hain.", "முதலில் வீட்டிற்கு வருவேன், பிறகு பார்ப்போம்.", "I will come home first, then we will see.", "Finishing the course means you have a repeatable way to catch anchors, time, and intent; it is not a fluency guarantee."))
    ]

    static func day(number: Int) -> CourseDay {
        allDays.first(where: { $0.number == number }) ?? allDays[0]
    }

    private static func prompt(
        _ id: String,
        _ phrase: String,
        _ tamil: String,
        _ english: String,
        _ anchor: String,
        _ pattern: String,
        _ note: String,
        _ question: String,
        _ choices: [String],
        _ correctChoice: String,
        _ mode: PromptMode,
        _ skill: SkillArea
    ) -> PhrasePrompt {
        PhrasePrompt(id: id, phrase: phrase, tamil: tamil, english: english, anchor: anchor, pattern: pattern, note: note, question: question, choices: choices, correctChoice: correctChoice, mode: mode, skill: skill)
    }

    private static func roleplay(
        _ id: String,
        _ title: String,
        _ setting: String,
        _ opening: String,
        _ openingTamil: String,
        _ openingEnglish: String,
        _ choices: [String],
        _ bestChoice: String,
        _ helpfulReplyTamil: String,
        _ helpfulReplyEnglish: String,
        _ tip: String
    ) -> RoleplayScenario {
        RoleplayScenario(id: id, title: title, setting: setting, opening: opening, openingTamil: openingTamil, openingEnglish: openingEnglish, choices: choices, bestChoice: bestChoice, helpfulReplyTamil: helpfulReplyTamil, helpfulReplyEnglish: helpfulReplyEnglish, tip: tip)
    }

    private static func makeDay(
        _ number: Int,
        _ title: String,
        _ tamilTitle: String,
        _ focus: String,
        _ outcome: String,
        _ prompts: [PhrasePrompt],
        _ roleplay: RoleplayScenario
    ) -> CourseDay {
        CourseDay(number: number, title: title, tamilTitle: tamilTitle, focus: focus, outcome: outcome, minutes: 12, prompts: prompts, roleplay: roleplay)
    }
}
